version: '3'

services:
  payload:
    build: .
    expose:
      - 3000
    networks:
      - payload_network
    volumes:
      - /var/payload-admin/media:/var/payload-admin/media
    working_dir: /home/node/app/
    command: node ./dist/server.js
    env_file:
      - .env
    restart: on-failure

  nginx:
    build: ./nginx
    networks:
      - payload_network
    volumes:
      - /var/payload-admin/media:/var/payload-admin/media
      - /var/merchant-bot/logs:/var/merchant-bot/logs
      - /var/welcome-bot/logs:/var/welcome-bot/logs
    ports:
      - '${PAYLOAD_PUBLIC_NGINX_PORT:-80}:80'
    depends_on:
      - payload
    restart: on-failure

networks:
  payload_network:
    driver: bridge
