version: '3'

services:

  payload:
    build: .
    ports:
      - "3002:3000"
    volumes:
      - /var/payload-admin/media:/var/payload-admin/media
    working_dir: /home/node/app/
    command: node ./dist/server.js
    env_file:
      - .env
